import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {applyEvent, resetCounters, buildTrace} from '../../../static/cmh-os/js/services/run-state.js';
const base = () => ({id:'r',workflowName:'w',status:'pending',createdAt:'2026-10-02T00:00:00Z',startedAt:null,limits:{},usage:{tokensIn:0,tokensOut:0,costUsd:null,iterations:0,elapsedSeconds:0,measured:false},steps:['a','b'].map(key=>({key,status:'pending',startedAt:null,tokensIn:0,tokensOut:0,dependencies:[],tools:[]})),artifacts:[]});
const event=(kind,key,payload={})=>({kind,stepKey:key,payload,seq:1,at:'2026-10-02T00:00:00Z'});
const metric=(key,input,output)=>event('model_metrics',key,{metrics:{input_tokens:input,output_tokens:output}});
test('lifecycle events do not measure usage or trace tokens',()=>{
 for(const kind of ['run_created','step_started']) {const e=event(kind,kind==='step_started'?'a':undefined); const s=applyEvent(base(),e); assert.equal(s.usage.measured,false); assert.equal(buildTrace(s,[e]).measured,false);}
});
test('numeric zero is a measured value',()=>{const e=metric('a',0,0);const s=applyEvent(base(),e);assert.equal(s.usage.measured,true);assert.equal(s.steps[0].tokensMeasured,true);assert.equal(buildTrace(s,[e]).measured,true);assert.equal(s.usage.tokensIn+s.usage.tokensOut,0);});
test('positive token measurements preserve sums',()=>{const es=[metric('a',7,3),metric('a',2,1)];const s=es.reduce(applyEvent,base());assert.equal(s.usage.tokensIn,9);assert.equal(s.usage.tokensOut,4);assert.equal(buildTrace(s,es).tokensIn,9);});
test('mixed measured and unmeasured steps never mark total measured',()=>{const es=[event('step_started','a'),metric('a',7,3),event('step_started','b')];const s=es.reduce(applyEvent,base());assert.equal(s.steps[0].tokensMeasured,true);assert.notEqual(s.steps[1].tokensMeasured,true);assert.equal(s.usage.measured,false);assert.equal(buildTrace(s,es).measured,false);});
test('each attempted step measured makes total available',()=>{const es=[event('step_started','a'),metric('a',7,3),event('step_started','b'),metric('b',0,0)];const s=es.reduce(applyEvent,base());assert.equal(s.usage.measured,true);assert.equal(buildTrace(s,es).measured,true);});
test('malformed metrics cannot demonstrate tokens, including after valid metrics',()=>{for(const pair of [[undefined,0],['7',3],[-1,0],[NaN,0],[0,Infinity]]){const bad=metric('a',...pair);const s=[bad,metric('a',0,0)].reduce(applyEvent,base());assert.equal(s.usage.measured,false);assert.equal(s.steps[0].tokensMeasured,false);assert.equal(buildTrace(s,[bad,metric('a',0,0)]).measured,false);}});
test('reset clears token evidence without mutating snapshot',()=>{const s=applyEvent(base(),metric('a',7,3));const fresh=resetCounters(s);assert.equal(fresh.steps[0].tokensMeasured,false);assert.equal(fresh.usage.measured,false);assert.equal(s.steps[0].tokensMeasured,true);});
test('production step token renderer distinguishes missing from measured zero',()=>{const text=readFileSync(new URL('../../../static/cmh-os/js/views/executions.js',import.meta.url),'utf8');const match=text.match(/render: \(s\) => (\(s\.tokensMeasured === true \? formatNumber\(s\.tokensIn \+ s\.tokensOut\) : '[^']*'\))/);assert.ok(match);const render=Function('formatNumber','return s => '+match[1])(String);assert.equal(render({tokensMeasured:true,tokensIn:7,tokensOut:3}),'10');assert.equal(render({tokensIn:0,tokensOut:0}),'\u2014');assert.equal(render({tokensMeasured:true,tokensIn:0,tokensOut:0}),'0');});
test('production aggregate token KPI hides mixed trace coverage',()=>{const text=readFileSync(new URL('../../../static/cmh-os/js/views/observability.js',import.meta.url),'utf8');const match=text.match(/value: (rows\.length > 0 && rows\.every\(\(r\) => r\.measured\) \? formatNumber\(rows\.reduce\(\(s, r\) => s \+ r\.tokensIn \+ r\.tokensOut, 0\)\) : '[^']*')/);assert.ok(match);const render=Function('formatNumber','return rows => '+match[1])(String);assert.equal(render([{measured:true,tokensIn:7,tokensOut:3},{measured:false,tokensIn:0,tokensOut:0}]),'\u2014');assert.equal(render([{measured:true,tokensIn:0,tokensOut:0}]),'0');});
